version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE_NAME}
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    depends_on:
      - db
      - mongo
    environment:
      MYSQL_DATABASE_URL: jdbc:mysql://db/${MYSQL_DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      MYSQL_DATABASE_USER: ${MYSQL_DATABASE_USER}
      MYSQL_DATABASE_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MONGO_DATABASE_URI: mongodb://mongo/${MYSQL_DATABASE_NAME}
      PORT: ${PORT}
      SUPERUSER_USERNAME: ${SUPERUSER_USERNAME}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
    ports:
      - ${PORT}:${PORT}
volumes:
  db_data:
  mongo_data: